linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/gotenberg/gotenberg/v8)
    skip-generated: true
    custom-order: true

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - exportloopref
    - gci
    - gofmt
    - goimports
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - importas
    - misspell
    - prealloc
    - promlinter
    #- sloglint
    - staticcheck
    - tenv
    - testableexamples
    - tparallel
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false

output:
  print-issued-lines: true
  print-linter-name: true
