name: Build and Push
description: Build and push Docker images
author: Julien Neuhart

inputs:
  github_token:
    description: The GitHub token
    required: true
    default: ${{ github.token }}
  docker_hub_username:
    description: The Docker Hub username
    required: true
  docker_hub_password:
    description: The Docker Hub password
    required: true
  platform:
    description: linux/amd64, linux/386, linux/arm64, linux/arm/v7
    required: true
  version:
    description: Gotenberg version
    required: true
  alternate_repository:
    description: Alternate repository to push the tags to
  dry_run:
    description: Dry run this action

outputs:
  tags:
    description: Comma separated list of tag
    value: ${{ steps.build_push.outputs.tags }}
  tags_cloud_run:
    description: Comma separated list of Cloud Run tags (linux/amd64 only)
    value: ${{ steps.build_push.outputs.tags_cloud_run }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Check out code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_password }}

    - name: Build and push ${{ inputs.platform }}
      id: build_push
      shell: bash
      run: |
        .github/actions/build-push/build-push.sh \
          --version "${{ inputs.version }}" \
          --platform "${{ inputs.platform }}" \
          --alternate-repository "${{ inputs.alternate_repository }}" \
          --dry-run "${{ inputs.dry_run }}"

    - name: Outputs
      shell: bash
      run: |
        echo "tags=${{ steps.build_push.outputs.tags }}"
        echo "tags_cloud_run=${{ steps.build_push.outputs.tags_cloud_run }}"
