on:
  workflow_call:
    inputs:
      gotenberg_version:
        type: string
        required: true
      alternate_repository:
        type: string
        default: ''

permissions:
  contents: read

jobs:
  delete:
    name: Delete Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Delete
        uses: gotenberg/gotenberg-release-action/actions/delete@main
        with:
          docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          version: ${{ inputs.gotenberg_version }}
          alternate_repository: ${{ inputs.alternate_repository }}
