name: ci
on:
  workflow_dispatch: {}
  push:
    branches:
      - main-bc
    tags:
      - v*
  pull_request:
    branches:
      - main-bc
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  docker:
    permissions:
      actions: read
      contents: read
      checks: write
      id-token: write
      security-events: write
    name: Docker
    uses: Onebrief/actions/.github/workflows/reusable-docker-build.yml@4c86a46e69127e0d361e95a5c2dc9b17964e405e
    secrets: inherit
    with:
      repository: onebrief/gotenberg
      dockerfile: build/Dockerfile.bc
