name: Continuous Delivery

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  release_amd64:
    name: Release linux/amd64
    uses: ./.github/workflows/__build-push.yml
    secrets: inherit
    with:
      runs_on: ubuntu-latest
      platform: linux/amd64
      gotenberg_version: ${{ github.event.release.tag_name }}

  release_386:
    name: Release linux/386
    uses: ./.github/workflows/__build-push.yml
    secrets: inherit
    with:
      runs_on: ubuntu-latest
      platform: linux/386
      gotenberg_version: ${{ github.event.release.tag_name }}

  release_arm64:
    name: Release linux/arm64
    uses: ./.github/workflows/__build-push.yml
    secrets: inherit
    with:
      runs_on: ubuntu-24.04-arm
      platform: linux/arm64
      gotenberg_version: ${{ github.event.release.tag_name }}

  release_arm_v7:
    name: Release linux/arm/v7
    uses: ./.github/workflows/__build-push.yml
    secrets: inherit
    with:
      runs_on: ubuntu-24.04-arm
      platform: linux/arm/v7
      gotenberg_version: ${{ github.event.release.tag_name }}

  merge_clean_release_tags:
    needs:
      - release_amd64
      - release_386
      - release_arm64
      - release_arm_v7
    name: Merge and clean release tags
    uses: ./.github/workflows/__merge-clean.yml
    secrets: inherit
    with:
      tags: "${{ needs.release_amd64.outputs.tags }},${{ needs.release_386.outputs.tags }},${{ needs.release_arm64.outputs.tags }},${{ needs.release_arm_v7.outputs.tags }}"
      alternate_registry: thecodingmachine
