name: Continuous Delivery

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release_amd64:
    name: Release linux/amd64
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.build_push.outputs.tags }}
      tags_cloud_run: ${{ steps.build_push.outputs.tags_cloud_run }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build and push
        id: build_push
        uses: ./.github/actions/build-push
        with:
          docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          version: ${{ github.event.release.tag_name }}
          platform: linux/amd64

  release_386:
    name: Release linux/386
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.build_push.outputs.tags }}
      tags_cloud_run: ${{ steps.build_push.outputs.tags_cloud_run }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build and push
        id: build_push
        uses: ./.github/actions/build-push
        with:
          docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          version: ${{ github.event.release.tag_name }}
          platform: linux/386

  release_arm64:
    name: Release linux/arm64
    runs-on: ubuntu-24.04-arm
    outputs:
      docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
      tags: ${{ steps.build_push.outputs.tags }}
      tags_cloud_run: ${{ steps.build_push.outputs.tags_cloud_run }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build and push
        id: build_push
        uses: ./.github/actions/build-push
        with:
          docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          version: ${{ github.event.release.tag_name }}
          platform: linux/arm64

  release_arm_v7:
    name: Release linux/arm/v7
    runs-on: ubuntu-24.04-arm
    outputs:
      tags: ${{ steps.build_push.outputs.tags }}
      tags_cloud_run: ${{ steps.build_push.outputs.tags_cloud_run }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build and push
        id: build_push
        uses: ./.github/actions/build-push
        with:
          docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          version: ${{ github.event.release.tag_name }}
          platform: linux/arm/v7

  merge_clean_release_tags:
    needs:
      - release_amd64
      - release_386
      - release_arm64
      - release_arm_v7
    name: Merge and clean release tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Merge
        uses: ./.github/actions/merge
        with:
          docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: "${{ needs.release_amd64.outputs.tags }},${{ needs.release_386.outputs.tags }},${{ needs.release_arm64.outputs.tags }},${{ needs.release_arm_v7.outputs.tags }}"
          alternate_registry: thecodingmachine

      - name: Clean
        uses: ./.github/actions/clean
        with:
          docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: "${{ needs.release_amd64.outputs.tags }},${{ needs.release_386.outputs.tags }},${{ needs.release_arm64.outputs.tags }},${{ needs.release_arm_v7.outputs.tags }}"
