on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        required: true
      platform:
        type: string
        required: true
      gotenberg_version:
        type: string
        required: true
      alternate_repository:
        type: string
        default: ''
    outputs:
      tags:
        value: ${{ jobs.gotenberg_build_push.outputs.tags }}

permissions:
  contents: read

jobs:
  gotenberg_build_push:
    runs-on: ${{ inputs.runs_on }}
    outputs:
      tags: ${{ steps.build_push.outputs.tags }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ inputs.platform }}
        id: build_push
        uses: gotenberg/gotenberg-release-action@main
        with:
          step: build_push
          version: ${{ inputs.gotenberg_version }}
          platform: ${{ inputs.platform }}
          alternate_repository: ${{ inputs.alternate_repository }}
