name: Pull Request Cleanup

on:
  pull_request:
    types: [ closed ]

permissions:
  contents: read

jobs:

  cleanup:
    name: Cleanup
    uses: ./.github/workflows/__delete.yml
    secrets: inherit
    with:
      gotenberg_version: pr-${{ github.event.pull_request.number }}
      alternate_repository: snapshot
